// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WPF_BO;

#nullable disable

namespace WPF_BO.Migrations
{
    [DbContext(typeof(wpfManagementContext))]
    [Migration("20240223044741_PC")]
    partial class PC
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WPF_BO.Account", b =>
                {
                    b.Property<short>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("userID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("UserId"), 1L, 1);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password");

                    b.Property<long>("Role")
                        .HasColumnType("bigint")
                        .HasColumnName("role");

                    b.Property<bool>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("status");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("username");

                    b.HasKey("UserId")
                        .HasName("accounts_userid_primary");

                    b.HasIndex(new[] { "UserId" }, "UQ__Accounts__CB9A1CDE4F738757")
                        .IsUnique();

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("WPF_BO.Category", b =>
                {
                    b.Property<short>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("categoryID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("CategoryId"), 1L, 1);

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("categoryName");

                    b.HasKey("CategoryId");

                    b.HasIndex(new[] { "CategoryId" }, "UQ__Category__23CAF1F980EFA6F4")
                        .IsUnique();

                    b.ToTable("Category", (string)null);
                });

            modelBuilder.Entity("WPF_BO.Pc", b =>
                {
                    b.Property<short>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("productID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("ProductId"), 1L, 1);

                    b.Property<short>("CategoryId")
                        .HasColumnType("smallint")
                        .HasColumnName("categoryID");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("ImageLink")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("imageLink");

                    b.Property<long>("Price")
                        .HasColumnType("bigint")
                        .HasColumnName("price");

                    b.Property<long?>("Review")
                        .HasColumnType("bigint")
                        .HasColumnName("review");

                    b.Property<bool>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("status");

                    b.Property<short?>("StoreId")
                        .HasColumnType("smallint")
                        .HasColumnName("storeID");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("title");

                    b.Property<short>("UserId")
                        .HasColumnType("smallint")
                        .HasColumnName("userID");

                    b.HasKey("ProductId")
                        .HasName("electronics_productid_primary");

                    b.HasIndex(new[] { "ProductId" }, "UQ__PC__2D10D14B3A00FD12")
                        .IsUnique();

                    b.HasIndex(new[] { "CategoryId" }, "pc_categoryid_index");

                    b.HasIndex(new[] { "StoreId" }, "pc_storeid_index");

                    b.HasIndex(new[] { "UserId" }, "pc_userid_index");

                    b.ToTable("PC", (string)null);
                });

            modelBuilder.Entity("WPF_BO.Store", b =>
                {
                    b.Property<short>("StoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("storeID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("StoreId"), 1L, 1);

                    b.Property<string>("StoreLocation")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("storeLocation");

                    b.HasKey("StoreId");

                    b.HasIndex(new[] { "StoreId" }, "UQ__Store__1EA716322F03347F")
                        .IsUnique();

                    b.ToTable("Store", (string)null);
                });

            modelBuilder.Entity("WPF_BO.Pc", b =>
                {
                    b.HasOne("WPF_BO.Category", "Category")
                        .WithMany("Pcs")
                        .HasForeignKey("CategoryId")
                        .IsRequired()
                        .HasConstraintName("pc_categoryid_foreign");

                    b.HasOne("WPF_BO.Store", "Store")
                        .WithMany("Pcs")
                        .HasForeignKey("StoreId")
                        .HasConstraintName("pc_storeid_foreign");

                    b.HasOne("WPF_BO.Account", "User")
                        .WithMany("Pcs")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("pc_userid_foreign");

                    b.Navigation("Category");

                    b.Navigation("Store");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WPF_BO.Account", b =>
                {
                    b.Navigation("Pcs");
                });

            modelBuilder.Entity("WPF_BO.Category", b =>
                {
                    b.Navigation("Pcs");
                });

            modelBuilder.Entity("WPF_BO.Store", b =>
                {
                    b.Navigation("Pcs");
                });
#pragma warning restore 612, 618
        }
    }
}
